### ISSUE TITLE
Quesstion about def cos(a,b)

### ISSUE THREAD

**Issue by alanzhong1** [zhmzm/FLTrust_pytorch#3] opened 2023-01-18 04:03 UTC
Hi,

Thanks for sharing the code. 
When I run your code, I find an exception when it calculates the cosine similarity in the function cos(a,b).
In the line res = np.sum(a*b.T)/((np.sqrt(np.sum(a * a.T)) + 1e-9) * (np.sqrt(np.sum(b * b.T))) + 1e-9).
It shows AttributeError: 'list' object has no attribute 'T'. 
When I try to convert the list into a NumPy with np.array, it tells me the input list is on GPU.
So, I use CPU() to transfer it from GPU to CPU. However, it tells me that list has no attribute 'cpu'.

I am not sure how to fix it, thanks for your help.

**Comment by zhmzm** [comment] 2023-01-18 04:26
Hi,
The issue is fixed now. You can download the new version. And I strongly recommend you use the code [here](https://github.com/zhmzm/FLAME), which also includes FLTrust and supports larger models like ResNet-18.

**Comment by alanzhong1** [comment] 2023-01-23 04:28
ok, thank you

**Closed as completed** 2023-04-18 03:17 UTC
