### ISSUE TITLE
low accuracy

### ISSUE THREAD

**Issue by fiora6** [zhmzm/FLTrust_pytorch#4] opened 2023-04-10 12:37 UTC
I run the code as suggested
 python FLTrustServer.py -nc 100 -cf 0.1 -E 5 -B 10 -mn mnist_2nn  -ncomm 1000 -iid 0 -lr 0.01 -vf 20 -g 0 
But after training completed, the accuracy is 0.09799998998641968.

**Comment by zhmzm** [comment] 2023-04-10 14:45
Hi,
did you log the accuracy in all rounds? I guess it has converged in early rounds, but the fltrust is not stable to maintain it in later rounds. I have also encountered that the global model is damaged after convergence.

**Comment by fiora6** [comment] 2023-04-11 10:57
> 

Yeah. I rerun it and find the same problem as you say. And it seems the attack codes are not included.  Could you provide it?

**Comment by zhmzm** [comment] 2023-04-11 12:12
The code for attacks is not included in this repo. I recommend the [repo](https://github.com/zhmzm/FLDetector_pytorch), which implements FLTrust and backdoor attacks as well. The repo is easier to understand and implement the attacks you need.

**Comment by fiora6** [comment] 2023-04-17 08:31
> 

Thanks. I see in that repo, many methods such as train_malicious_badnet in class LocalUpdate don't show in main_fed.py. When we set args.attack = 'badnet', should I change local.train to local.train_malicious_badnet in main_fed.py?

**Comment by zhmzm** [comment] 2023-04-18 03:25
In main_fed.py, the function attacker() is used to implement attacks.
https://github.com/zhmzm/FLDetector_pytorch/blob/75f1413d4d21fdb5923e051d52bc02a653d7f81f/models/Attacker.py#L158-L181

**Comment by fiora6** [comment] 2023-04-18 11:23
> In main_fed.py, the function attacker() is used to implement attacks. https://github.com/zhmzm/FLDetector_pytorch/blob/75f1413d4d21fdb5923e051d52bc02a653d7f81f/models/Attacker.py#L158-L181

It seems w and loss are None in function attacker(), and the variable local in attacker() hasn't been called.

**Comment by zhmzm** [comment] 2023-04-18 13:21
Yes, you are right. The issue is fixed with the line https://github.com/zhmzm/FLDetector_pytorch/blob/c8aeb02c0aa0286dbc046e2c40050e86383d642f/models/Attacker.py#L173. Thanks for your report. Could you try it again?

**Comment by fiora6** [comment] 2023-04-22 08:39
That's ok now. And when I set args.attack = 'labelflip', it shows 'Error Attack Method'. Can you fix it?

**Comment by zhmzm** [comment] 2023-04-22 13:36
I will add it when I am available, but not recently. I think you can implement it easily following my code. 

https://github.com/zhmzm/FLDetector_pytorch/blob/c8aeb02c0aa0286dbc046e2c40050e86383d642f/models/MaliciousUpdate.py#L122-L129

Add a function here, where you can flip the ground truth labels $x$ to $n-x$ ($9-x$ in MNIST and CIFAR-10).

**Comment by Longchao1047027852** [comment] 2023-05-09 03:05
global_parameters[var] += (sum_parameters[var] / FLTrustTotalScore + 1e-9)你好，这行代码是不是存在计算问题，1e-9的位置是否错误；应该改为global_parameters[var] += (sum_parameters[var] / (FLTrustTotalScore + 1e-9))

**Comment by zhmzm** [comment] 2023-05-10 02:31
> global_parameters[var] += (sum_parameters[var] / FLTrustTotalScore + 1e-9)你好，这行代码是不是存在计算问题，1e-9的位置是否错误；应该改为global_parameters[var] += (sum_parameters[var] / (FLTrustTotalScore + 1e-9))

You are right. It should be 
https://github.com/zhmzm/FLTrust_pytorch/blob/ace6acbbb6a452d50b4ec495d73ef2fdeb944fda/src/FLTrustServer.py#L131
Thanks for your report.

**Comment by Luluuu1014** [comment] 2024-02-28 09:41
> global_parameters[var] += (sum_parameters[var] / FLTrustTotalScore + 1e-9)你好，这行代码是不是存在计算问题，1e-9的位置是否错误；应该改为global_parameters[var] += (sum_parameters[var] / (FLTrustTotalScore + 1e-9))

请问您复现成功了吗，是否可以分享一下

**Comment by Luluuu1014** [comment] 2024-02-28 09:41
> That's ok now. And when I set args.attack = 'labelflip', it shows 'Error Attack Method'. Can you fix it?

请问您复现成功了吗，是否可以分享一下

**Comment by Longchao1047027852** [comment] 2024-02-28 12:35
不好意思，这个课题是我同门那时候进行的。具体情况我也知道的不是很多。我只知道它这个框架貌似存在bug。&nbsp;


1047027852
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年2月28日(星期三) 下午5:41
收件人: "zhmzm/FLTrust_pytorch";
抄送: "Comment";
主题: Re: [zhmzm/FLTrust_pytorch] low accuracy (Issue #4)





  
That's ok now. And when I set args.attack = 'labelflip', it shows 'Error Attack Method'. Can you fix it?
  
请问您复现成功了吗，是否可以分享一下
 
&mdash;

**Comment by Luluuu1014** [comment] 2024-02-29 11:55
> 好意思，这个课题是
好的好的谢谢

**Closed as completed** 2024-04-23 15:11 UTC

**Comment by Luluuu1014** [comment] 2024-07-25 15:29
> I run the code as suggested python FLTrustServer.py -nc 100 -cf 0.1 -E 5 -B 10 -mn mnist_2nn -ncomm 1000 -iid 0 -lr 0.01 -vf 20 -g 0 But after training completed, the accuracy is 0.09799998998641968.

不好意思打扰了，请问这个问题你有解决吗？0.9094001007080078, 0.9138001251220703, 0.9191999816894532, 0.9222998046875, 0.09799999237060547我的准确率总是这样，某一轮突然就会降至0.09左右，学习率越大出现这个轮次会越靠前。

**Comment by Luluuu1014** [comment] 2024-07-25 15:30
> I run the code as suggested python FLTrustServer.py -nc 100 -cf 0.1 -E 5 -B 10 -mn mnist_2nn -ncomm 1000 -iid 0 -lr 0.01 -vf 20 -g 0 But after training completed, the accuracy is 0.09799998998641968.

不好意思打扰了，请问这个问题你有解决吗？0.9094001007080078, 0.9138001251220703, 0.9191999816894532, 0.9222998046875, 0.09799999237060547我的准确率总是这样，某一轮突然就会降至0.09左右，学习率越大出现这个轮次会越靠前。
